import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../Navbar/Navbar';
import { ThemeProvider } from '@/components/ThemeProvider/Theme';
import { SessionProvider } from '@/components/SessionProvider';
import { auth } from "../auth"
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Form App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await auth()
  return (
    <html lang="en">
    <body className={inter.className}>
      <ThemeProvider>
        <SessionProvider session={session}>
          <Navbar />
          {children}
        </SessionProvider>
      </ThemeProvider>
    </body>
  </html>
  );
}